# Generated by Django 2.0.4 on 2018-04-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180423_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relatez',
        ),
        migrations.AddField(
            model_name='product',
            name='related',
            field=models.ManyToManyField(related_name='_product_related_+', to='profiles.product'),
        ),
    ]
