# Generated by Django 2.0.4 on 2018-04-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180423_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_product_related_+', to='profiles.product'),
        ),
    ]
